### ISSUE TITLE
pthread_create in lpmd_proc.c is not being checked for pthread creation failure

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-lpmd#15]
I ran clang scan build on the current lpmd repo tip and it found just one issue:

```
File:	lpmd_proc.c
Warning:	[line 662, column 2](http://127.0.0.1:8181/report-424c19.html#EndPath)
Value stored to 'ret' is never read
```

`ret = pthread_create (&lpmd_core_main, &lpmd_attr, lpmd_core_main_loop, NULL);`

the ret is not being checked for failure, pthread_create can fail, so it's worth checking and handling this failure mode.

**Comment by zhang-rui** [comment]
Fix merged. Thanks for raising this @ColinIanKing
