### ISSUE TITLE
dbus_glib_global_set_disable_legacy_property_access: command not found

### ISSUE THREAD

**Issue by zhang-rui** [intel/intel-lpmd#35]
When I run ./configure, I got

checking for dbus-glib-1 >= 0.94... yes
./configure: line 3930: dbus_glib_global_set_disable_legacy_property_access: command not found

And this is introduced by this commit

commit d66428a04777fcf0615ec14e0d3c347106e3a6ea (HEAD)
Author:     Tomasz Kłoczko <kloczek@github.com>
AuthorDate: Sat Feb 10 13:46:53 2024 +0000
Commit:     Tomasz Kłoczko <kloczek@github.com>
CommitDate: Sat Feb 10 13:46:53 2024 +0000

    automake and auto conf improvements
    
    - remove not used `include $(GLIB_MAKEFILE)` lines
    - use automake to build intel_lpmd_control
    - use autoconf AC_CONFIG_FILES() to generate data/intel_lpmd.service and
      data/org.freedesktop.intel_lpmd.service instead custom sed rules
    - more [] quotes in configure ac
    - use $rundir and bumped minimum autoconf version required to 2.70
    - remove use AM_CFLAGS in main Makefile.am
    - remove . from SUBDIRS in main Makefile.am
    - use PKG_CHECK_MODULES() to detect dbus-glib-1
    - remove redundant AC_SUBST(FOO_CFLAGS) and AC_SUBST(FOO_LIBS)
      (PKG_CHECK_MODULES() adds that automatically)
    
    Signed-off-by: Tomasz Kłoczko <kloczek@github.com>

@kloczek , can you help check this?

**Comment by zhang-rui** [comment]
please kindly help check this issue @kloczek

**Comment by kloczek** [comment]
Just found that my automation was able automatically process new 0.0.5 github release email notification.
If that fix has been included in that version .. ItWorks™️ .

**Comment by zhang-rui** [comment]
> Just found that my automation was able automatically process new 0.0.5 github release email notification. If that fix has been included in that version .. ItWorks™️ .

what do you mean? which fix are you referring to?
for me, I run into this issue but nothing breaks for me.

**Comment by zhang-rui** [comment]
Problem fixed in latest release
