### ISSUE TITLE
HFI always reports zeroes for LPE cores on Meteor Lake

### ISSUE THREAD

**Issue by vient** [intel/intel-lpmd#37]
Trying to understand what this daemon can do, I turned on all HFI settings, debug logs, and saw this
```
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU   0:  PERF [ 268]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU   2:  PERF [ 268]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU   4:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU   6:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU   8:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  10:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  12:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  13:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  14:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  15:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  16:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  17:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  18:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  19:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  20:  PERF [   0]  EFF [   0]  TYPE [BAN]
Jun 13 01:49:23 vient-laptop intel_lpmd[200681]:    CPU  21:  PERF [   0]  EFF [   0]  TYPE [BAN]

Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU   0:  PERF [   0]  EFF [   0]  TYPE [BAN]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU   2:  PERF [   0]  EFF [   0]  TYPE [BAN]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU   4:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU   6:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU   8:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  10:  PERF [ 252]  EFF [ 188]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  12:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  13:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  14:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  15:  PERF [ 164]  EFF [ 592]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  16:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  17:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  18:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  19:  PERF [ 164]  EFF [ 516]  TYPE [NOR]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  20:  PERF [   0]  EFF [   0]  TYPE [BAN]
Jun 13 01:49:25 vient-laptop intel_lpmd[200681]:    CPU  21:  PERF [   0]  EFF [   0]  TYPE [BAN]
```
This is a 155H with SMT off
```
Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          46 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   22
  On-line CPU(s) list:    0,2,4,6,8,10,12-21
  Off-line CPU(s) list:   1,3,5,7,9,11
Vendor ID:                GenuineIntel
  BIOS Vendor ID:         Intel(R) Corporation
  Model name:             Intel(R) Core(TM) Ultra 7 155H
  ```
Using CachyOS kernel 6.9.1, just in case.

Cores 20-21 always report zeroes in both fields - is it normal? LPE cores should get the highest EFF value, and they get zero?
Also weird that cores 0,2 sometimes get both zeroes too, these are performance cores with slightly higher possible clocks then the other four performance cores 4,6,8,10, as I understand.

**Comment by zhang-rui** [comment]
I do see LPE cores with 0/0 in some cases, but not always. When this happens, usually the system is under certain load and firmware tells us to use compute die CPUs only.

How do you tune SMT off? via BIOS or OS knobs?
I didn't run with such configurations previously.

**Comment by pouv02** [comment]
How do you turn on the HFI settings? 

Where did you get this output? Thanks.
> This is a 155H with SMT off
> 
> ```
> Architecture:             x86_64
>   CPU op-mode(s):         32-bit, 64-bit
>   Address sizes:          46 bits physical, 48 bits virtual
>   Byte Order:             Little Endian
> CPU(s):                   22
>   On-line CPU(s) list:    0,2,4,6,8,10,12-21
>   Off-line CPU(s) list:   1,3,5,7,9,11
> Vendor ID:                GenuineIntel
>   BIOS Vendor ID:         Intel(R) Corporation
>   Model name:             Intel(R) Core(TM) Ultra 7 155H
> ```
>

**Comment by zhang-rui** [comment]
> How do you turn on the HFI settings?

Enable the HFI monitor in the config file by changing <HfiLpmEnable>0</HfiLpmEnable> to <HfiLpmEnable>1</HfiLpmEnable>
> 
> Where did you get this output? Thanks.

Looks like lscpu output.

**Comment by vient** [comment]
Yes, this is lscpu. By "turning on" settings I meant setting HfiLpmEnable, HfiLpmEnable and HfiSuvEnable to 1 in intel_lpmd_config.xml.

> How do you tune SMT off? 

By passing `nosmt` to kernel command line. Full command line, just in case
```
BOOT_IMAGE=/vmlinuz-6.9.1 root=/dev/mapper/ubuntu--vg-ubuntu--lv ro quiet splash nosmt sysrq_always_enabled=1 mitigations=off i915.mitigations=off transparent_hugepage=always iommu=pt intel_iommu=on nohz_full=1-19 rcu_nocbs=0-N cryptomgr.notests no_timer_check noreplace-smp page_alloc.shuffle=1 rcupdate.rcu_expedited=1 tsc=reliable crashkernel=2G-4G:320M,4G-32G:512M,32G-64G:1024M,64G-128G:2048M,128G-:4096M vt.handoff=7
```

**Comment by zhang-rui** [comment]
what if you enable HT?
I'm not sure if this is the expected output of firmware, or disabling HT via software confuses it.

But anyway, this is not an intel_lpmd problem, unless lpmd doesn't put the system to proper state based on the given HFI hints.

**Comment by zhang-rui** [comment]
What workload are you running?
we do see similar HFI hints in some scenarios, but we also see the LPE cores with highest perf under idle.

**Comment by zhang-rui** [comment]
Issue closed as this is not intel_lpmd' problem.
And we do need firmware reports similar hints in certain scenarios.

**Comment by vient** [comment]
Yeah, I just asked in case you know something about it.

> What workload are you running?

I tried both idle and full load, on battery and on AC. The difference is between low and high load - if load is low, P-cores may report zeroes. LPE-cores always report zeroes in all scenarios.
