### ISSUE TITLE
Compiler warning about  "above array bounds "

### ISSUE THREAD

**Issue by smallorange** [intel/intel-lpmd#47]
Hi,

I tried to build 0.0.6 but the compiler complained about the warning message shown below

```
make[2]: Leaving directory '/builddir/build/BUILD/intel-lpmd-0.0.6'
In file included from /usr/include/glib-2.0/glib.h:64,
                 from src/lpmd.h:48,
                 from src/lpmd_cpu.c:52:
src/lpmd_cpu.c: In function ‘add_cpu’:
src/lpmd_cpu.c:408:66: error: array subscript 8 is above array bounds of ‘struct lpm_cpus[7]’ [-Werror=array-bounds=]
  408 |                 lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
      |                                                          ~~~~~~~~^~~~~
src/lpmd_cpu.c:67:24: note: while referencing ‘cpumasks’
   67 | static struct lpm_cpus cpumasks[CPUMASK_MAX] = {
      |                        ^~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:686: src/intel_lpmd-lpmd_cpu.o] Error 1
make[1]: *** [Makefile:868: all-recursive] Error 1
make: *** [Makefile:459: all] Error 2
```

Thank you :)

**Comment by zhang-rui** [comment]
Interesting, I cannot reproduce this issue locally, and I don't see how add_cpu() can be invoked with idx == 8.

@smallorange , this is not a new regression, right? can you check if earlier version like 0.0.3/0.0.5 also have this issue?

And do you have any tips to reproduce this issue?

**Comment by smallorange** [comment]
The compiler parameter  [-Werror=array-bounds=] (-Warray-bounds) checks the array index and find the potential "above array bound" errors from the scripts.

For example, at the line [405](https://github.com/intel/intel-lpmd/blob/main/src/lpmd_cpu.c#L405]), the potential value of `idx` can be 0-7 (8 elements). Considering line [67](https://github.com/intel/intel-lpmd/blob/main/src/lpmd_cpu.c#L67), there are 7 items in the `struct lpm_cpus cpumasks[CPUMASK_MAX]` (CPUMASK_MAX = 7). 

```
(line 405 in lpmd_cpu.c)
	if (idx == CPUMASK_LPM_DEFAULT)
		lpmd_log_info ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
	else
		lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, CPU); <--- here. if idx == 7 
```
As shown in the code above, if idx == CPUMASK_MAX (7), the "above array bound" error will happen. 

I think you need check the array index value and then get the value from the array.

I have made a patch to fix it. 
```
 src/lpmd_cpu.c | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

diff --git a/src/lpmd_cpu.c b/src/lpmd_cpu.c
index 310bf65..808ae4b 100644
--- a/src/lpmd_cpu.c
+++ b/src/lpmd_cpu.c
@@ -402,10 +402,14 @@ int add_cpu(int cpu, enum cpumask_idx idx)
        if (idx & (CPUMASK_HFI | CPUMASK_HFI_SUV | CPUMASK_HFI_BANNED))
                return 0;

-       if (idx == CPUMASK_LPM_DEFAULT)
+       if (idx == CPUMASK_LPM_DEFAULT) {
                lpmd_log_info ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
-       else
-               lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
+       } else {
+               if (idx < CPUMASK_MAX)
+                       lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
+               else
+                       lpmd_log_debug ("\tIncorrect CPU ID for CPU%d\n", cpu);
+       }

        return 0;
 }

```

**Comment by zhang-rui** [comment]
> The compiler parameter [-Werror=array-bounds=] (-Warray-bounds) checks the array index and find the potential "above array bound" errors from the scripts.

Yes. I enabled this one but still cannot reproduce it.

gcc -DHAVE_CONFIG_H -I.  -I./src -DTDLOCALEDIR=\"/usr/local/share/locale\" -DGLIB_SUPPORT  -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -I/usr/include/libxml2 -DTDRUNDIR=\"/usr/local/var/run/intel_lpmd\" -DTDCONFDIR=\"/usr/local/etc/intel_lpmd\" -Werror=array-bounds -I/usr/include/libnl3 -I/usr/include/libnl3  -I src **-Werror=array-bounds** -MT src/intel_lpmd-lpmd_cpu.o -MD -MP -MF src/.deps/intel_lpmd-lpmd_cpu.Tpo -c -o src/intel_lpmd-lpmd_cpu.o `test -f 'src/lpmd_cpu.c' || echo './'`src/lpmd_cpu.c

> 
> For example, at the line [405](https://github.com/intel/intel-lpmd/blob/main/src/lpmd_cpu.c#L405%5D), the potential value of `idx` can be 0-7 (8 elements). Considering line [67](https://github.com/intel/intel-lpmd/blob/main/src/lpmd_cpu.c#L67), there are 7 items in the `struct lpm_cpus cpumasks[CPUMASK_MAX]` (CPUMASK_MAX = 7).
> 
> ```
> (line 405 in lpmd_cpu.c)
> 	if (idx == CPUMASK_LPM_DEFAULT)
> 		lpmd_log_info ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
> 	else
> 		lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, CPU); <--- here. if idx == 7 
> ```
> 
> As shown in the code above, if idx == CPUMASK_MAX (7), the "above array bound" error will happen.
> 

Okay, for this sense, it could be a potential risk.
Although add_cpu() can never be called with idx equals CPUMASK_MAX.

> You need to check the array index value and then get the value from the array, I think.
> 
> I have made a patch to fix it. I only test the idx value but I think you may fix it with a different approach.
> 
can you send a PR for this fix?

thanks,
rui
> ```
>  src/lpmd_cpu.c | 10 +++++++---
>  1 file changed, 7 insertions(+), 3 deletions(-)
> 
> diff --git a/src/lpmd_cpu.c b/src/lpmd_cpu.c
> index 310bf65..808ae4b 100644
> --- a/src/lpmd_cpu.c
> +++ b/src/lpmd_cpu.c
> @@ -402,10 +402,14 @@ int add_cpu(int cpu, enum cpumask_idx idx)
>         if (idx & (CPUMASK_HFI | CPUMASK_HFI_SUV | CPUMASK_HFI_BANNED))
>                 return 0;
> 
> -       if (idx == CPUMASK_LPM_DEFAULT)
> +       if (idx == CPUMASK_LPM_DEFAULT) {
>                 lpmd_log_info ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
> -       else
> -               lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
> +       } else {
> +               if (idx < CPUMASK_MAX)
> +                       lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
> +               else
> +                       lpmd_log_debug ("\tIncorrect CPU ID for CPU%d\n", cpu);
> +       }
> 
>         return 0;
>  }
> ```

**Comment by smallorange** [comment]
OKay
