### ISSUE TITLE
infinite loop in src/lpmd_hfi.c

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-lpmd#5]
src/lpmd_hfi.c has the following infinite loop:

```
        while (err > 0)
                nl_recvmsgs (drv->nl_handle, cb);
```

if err is > 0 then it's not being re-assigned in the loop and it will spin in the loop infinitely.

**Comment by zhang-rui** [comment]
nl_cb_err (cb, NL_CB_CUSTOM, error_handler, &err);
        nl_cb_set (cb, NL_CB_FINISH, NL_CB_CUSTOM, finish_handler, &err);
        nl_cb_set (cb, NL_CB_ACK, NL_CB_CUSTOM, ack_handler, &err);
        ...
        while (err > 0)
                nl_recvmsgs (drv->nl_handle, cb);

The address of err is parsed to the callbacks above, and the callbacks can modify the 'err' value to quit the loop.
