### ISSUE TITLE
[question]is there conflicts with other tools ?

### ISSUE THREAD

**Issue by user7z** [intel/intel-lpmd#65]
Hi guys , i wonder if there is conflicts with other tools like , thermald & tlp ?

**Comment by AlexDaichendt** [comment]
Also, how does this relate to a scheduler like bpfland? Does it conflict?

**Comment by zhang-rui** [comment]
AFAICS, it doesn't conflict with thermald.
I did a brief check of tlp. lpmd mains isolate CPUs/IRQs and change EPP/EPB values, and none of these are touched by tlp. So I don't think there is a conflict.

**Comment by zhang-rui** [comment]
> Also, how does this relate to a scheduler like bpfland? Does it conflict?

You can think of a user using cgroup settings. lpmd can isolate some CPUs so the kernel scheduler is only aware of the "active" CPUs. When this happens, kernel scheduler will rebuild sched domains and do schedule/balance based on that..

for "bpfland", are you referring to bpf based sched_ext?

**Comment by AlexDaichendt** [comment]
@zhang-rui 

Right, thank you for the elaboration. This critical piece of information is missing in the Readme.

Without any config the tool does nothing which made me think there is a conflict. After configuring my e cores in the configuration file, the tool works flawlessly. 

Bpfland https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_bpfland/README.md
