### ISSUE TITLE
project missing description and information about what lpmd actually does

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-lpmd#7]
Hi,

Minor issue, it would be super-useful if there was more information about the project, e.g. a short description and explanation of what the project is aiming to achieve.

**Comment by zhang-rui** [comment]
Where should we put this info? README or man page or some other places?

**Comment by ColinIanKing** [comment]
README.md is the normal place, for example: https://github.com/ColinIanKing/forkstat/#readme - this is a README.md (markdown) file containing project details.

**Comment by zhang-rui** [comment]
Problem solved in https://github.com/intel/intel-lpmd/pull/9
